version: '3.9'
networks:
  app-network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forms-backend
    command: >
      sh -c "
        uv run manage.py migrate &&
        uv run manage.py collectstatic --noinput &&
        uv run manage.py runserver 0.0.0.0:8028
      "
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8028:8028"
    env_file:
      - .env
    networks:
      - app-network

  #  db:
  #    image: postgres:15
  #    env_file: .env
  #    volumes:
  #      - pgdata:/var/lib/postgresql/data
  #    ports:
  #      - "5433:5432"
  #    networks:
  #      - app-network

  minio-init:
    image: alpine:latest
    entrypoint: >
      /bin/sh -c "
      apk add --no-cache curl &&
      curl -O https://dl.min.io/client/mc/release/linux-amd64/mc &&
      chmod +x mc &&
      ./mc alias set external http://146.255.188.248:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} &&
      ./mc mb external/local-bucket-form || true &&
      ./mc anonymous set download external/local-bucket-form || true
      ./mc mirror src/staticfiles external/local-bucket-form
      "
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - app-network
volumes:
  pgdata: