version: '3.9'
networks:
  app-network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forms-backend
    command: >
      sh -c "
        uv run manage.py migrate &&
        uv run manage.py collectstatic --noinput &&
        uv run manage.py runserver 0.0.0.0:8028
      "
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8028:8028"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5434"
    networks:
      - app-network

volumes:
  pgdata: