# Generated by Django 5.2.1 on 2025-05-30 12:21

import config.storages
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Динамическая форма',
                'verbose_name_plural': 'Динамические формы',
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('choice_value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ответ из формы',
                'verbose_name_plural': 'Ответы из форм',
            },
        ),
        migrations.CreateModel(
            name='FileValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=config.storages.MinIOMediaStorage(), upload_to='forms/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_image', models.BooleanField(default=False)),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_values', to='form.fieldvalue')),
            ],
            options={
                'verbose_name': 'Файл из ответа формы',
                'verbose_name_plural': 'Файлы из ответов на формы',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('select', 'Dropdown'), ('checkbox', 'Multiple Choice'), ('file', 'File Upload'), ('image', 'Image Upload')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form.dynamicform')),
            ],
            options={
                'verbose_name': 'Поле формы',
                'verbose_name_plural': 'Поля форм',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formfield'),
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form.dynamicform')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Аутентифицированный пользователь')),
            ],
            options={
                'verbose_name': 'Данные формы пользователя',
                'verbose_name_plural': 'Данные форм пользователей',
                'unique_together': {('user', 'session_key')},
            },
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='form.formsubmission'),
        ),
        migrations.CreateModel(
            name='HistoricalFormSubmission',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('form', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='form.dynamicform')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Аутентифицированный пользователь')),
            ],
            options={
                'verbose_name': 'historical Данные формы пользователя',
                'verbose_name_plural': 'historical Данные форм пользователей',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
